### ISSUE TITLE
[BUG]: Does this work on Apple Silicon

### ISSUE THREAD

**Issue by algebravic** [nexus-xyz/nexus-zkvm#293] opened 2024-12-06 17:03 UTC
### Program Information

```
#![cfg_attr(target_arch = "riscv32", no_std, no_main)]

fn fib(n: u32) -> u32 {
    match n {
        0 => 0,
        1 => 1,
        _ => fib(n - 1) + fib(n - 2),
    }
}

#[nexus_rt::main]
fn main() {
    let n = 7;
    let result = fib(n);
    assert_eq!(result, 13);
}
```

### Project Information

I was just trying the recommended test program.

### Reproduction Steps

```
rustup target add riscv32i-unknown-none-elf
cargo install --git https://github.com/nexus-xyz/nexus-zkvm cargo-nexus --tag 'v0.2.4'
cargo nexus new nexus-project
```
changed `main.rs` to the program given above
and then ran `cargo nexus run`

### What is expected?

"The command should run successfully"

### What is actually happening?

```
info: component 'rust-std' for target 'riscv32i-unknown-none-elf' is up to date
Victors-iMac:nexus-project victorsmiller$ cargo nexus run
   Compiling proc-macro2 v1.0.92
   Compiling indexmap v2.7.0
   Compiling serde v1.0.215
   Compiling syn v1.0.109
   Compiling cobs v0.2.3
   Compiling nexus-rt v0.2.4 (https://github.com/nexus-xyz/nexus-zkvm.git#0b787f2e)
error[E0463]: can't find crate for `core`
  |
  = note: the `riscv32i-unknown-none-elf` target may not be installed
  = help: consider downloading the target with `rustup target add riscv32i-unknown-none-elf`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cobs` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: cargo didn't exit successfully: exit status: 101
```

### System Information

iMac running 15.1.1 (24B91). cargo version 1.83.0, rustup 1.27.1, rustc 1.77.0

**Comment by sjudson** [comment] 2024-12-06 20:14
A lot of our development team uses apple sillicon, so that shouldn't be the issue. But I will attempt to replicate for the demonstrated issue.

**Comment by sjudson** [comment] 2024-12-06 20:31
@algebravic I'm having trouble reproducing on an M3 Pro running 15.1.1. May I ask what the output is if you sequentially run:

```bash
$ rustup target remove riscv32i-unknown-none-elf
$ rustup target add riscv32i-unknown-none-elf
```

**Comment by algebravic** [comment] 2024-12-06 20:50
I already tried that. Same result

**Comment by sjudson** [comment] 2024-12-06 20:52
@algebravic does it not provide any debugging information? I see:

```bash
*[master][~/Code/nexus-project]$ rustup target remove riscv32i-unknown-none-elf
info: syncing channel updates for '1.77.0-aarch64-apple-darwin'
info: latest update on 2024-03-21, rust version 1.77.0 (aedd173a2 2024-03-17)
info: downloading component 'rust-std' for 'riscv32i-unknown-none-elf'
info: installing component 'rust-std' for 'riscv32i-unknown-none-elf'
info: removing component 'rust-std' for 'riscv32i-unknown-none-elf'
*[master][~/Code/nexus-project]$ rustup target add riscv32i-unknown-none-elf   
info: syncing channel updates for '1.77.0-aarch64-apple-darwin'
info: latest update on 2024-03-21, rust version 1.77.0 (aedd173a2 2024-03-17)
info: downloading component 'rust-std' for 'riscv32i-unknown-none-elf'
info: installing component 'rust-std' for 'riscv32i-unknown-none-elf'
info: component 'rust-std' for target 'riscv32i-unknown-none-elf' is up to date
```

**Comment by algebravic** [comment] 2024-12-06 21:00
Here's what happens:

```
rustup target remove riscv32i-unknown-none-elf
info: removing component 'rust-std' for 'riscv32i-unknown-none-elf'
bash-3.2$ rustup target add riscv32i-unknown-none-elf
info: syncing channel updates for '1.77.0-aarch64-apple-darwin'
info: latest update on 2024-03-21, rust version 1.77.0 (aedd173a2
2024-03-17)
info: downloading component 'rust-std' for 'riscv32i-unknown-none-elf'
info: installing component 'rust-std' for 'riscv32i-unknown-none-elf'
info: component 'rust-std' for target 'riscv32i-unknown-none-elf' is up to
date
bash-3.2$ cargo nexus run
   Compiling cobs v0.2.3
   Compiling serde v1.0.215
error[E0463]: can't find crate for `core`
  |
  = note: the `riscv32i-unknown-none-elf` target may not be installed
  = help: consider downloading the target with `rustup target add
riscv32i-unknown-none-elf`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cobs` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `serde` (lib) due to 1 previous error
Error: cargo didn't exit successfully: exit status: 101
```

**Comment by sjudson** [comment] 2024-12-06 21:11
@algebravic 

Thank you for the additional information. The error appears very strange, as you can see it's happening much further down the dependency tree with widely-used packages that are a central part of the Rust ecosystem: the `serde` package is unable to find `core` to depend on and therefore failing to build before we even get to anything with the zkVM code. I am not even certain (other than a missing target, which I agree you do not appear to have) how a Rust installation wouldn't be able to find `core`, given that it is the keystone of the language ecosystem.

Unfortunately I don't know if there is any way in which we can be helpful: this seems like a problem with your underlying Rust installation, and not with our codebase. As noted, I've been able to successfully install and run the zkVM using the same instructions you followed above on an Apple Silicon machine running the same OS version while trying to reproduce your issue.

I'm going to close this issue for now since it does not appear to be an issue with our code, but will happily reopen it if you're able to provide more steps that enable us to reproduce the issue.

**Closed by sjudson** 2024-12-06 21:11 UTC
Labels: bug

**Comment by algebravic** [comment] 2024-12-06 22:21
I've installed rustup and rust using homebrew. I noticed that `cargo
--version` gives `cargo 1.83.0`. However, I noticed that the
`rust-toolchain.toml` has a line `channel = "1.77.0"`. Could that be
the problem? I tried
`rustup default 1.83.0` and `rustup default 1.7.0`, but both give the
same error when I type `cargo nexus run`.

**Comment by algebravic** [comment] 2024-12-06 22:54
I *finally* got this running. Here were the problems:
1) I had installed rustup and rust using homebrew. I uninstalled both,
and installed rust according to the recommended way using curl, etc.
2) The version that it installed was 1.83.0, but, apparently, zkVM
wants to work with 1.77.0. This necessitated by doing `rustup default
1.77.0` and then removing Cargo.lock in the directory i had just
created.
When I was using 1.83.0 it complained about the version in Cargo.lock.
Perhaps you should update the directions to say that the user must use
1.77.0 (or is that right?)
