### ISSUE TITLE
Cargo Run Error

### ISSUE THREAD

**Issue by MrHIB** [nexus-xyz/nexus-zkvm#173] opened 2024-06-11 06:38 UTC
How to solve it?

**Comment by sjudson** [comment] 2024-06-11 12:25
We would need more information about the specific error you are seeing.

Please see: https://github.com/nexus-xyz/nexus-zkvm/blob/main/CONTRIBUTING.md#submitting-a-bug-report for an explanation of what information is most helpful for us to help resolve issues with the code.

**Comment by ava-world** [comment] 2024-06-12 13:10
Cargo run error occurrs due to variety of reasons, I will assume you are using a Linux distribution.

If yes,

I would suggest you switch to the Linux system (Ubuntu) 22.04, you will experience no such error.

I would currently have no response for a MacBook if that is your current machine 

Anyways you are welcome to give more information, like the error logs or screenshot so you can get a substantial and more targeted response

**Comment by slumber** [comment] 2024-06-12 13:59
Please be more specific when filing an issue, so we can reproduce the problem.

Closing for now.

**Closed by slumber** 2024-06-12 13:59 UTC
